[project]
name = "spatial-workshop-2025"
version = "0.0.1"
description = "Workshop on 3D spatial omics data"
authors = [
    { name = "Luca Marconato", email = "luca.marconato@scverse.org" }
]
requires-python = ">=3.12"
# note: igneous-pipeline is licensed under GPL-3.0
dependencies = [
    "tissue-map-tools @ git+https://github.com/hms-dbmi/tissue-map-tools@fixes-for-workshop",
    "spatialdata @ git+https://github.com/scverse/spatialdata@dask-unpinned-3d-support",
    "napari-spatialdata @ git+https://github.com/scverse/napari-spatialdata@better_3d",
    "easy_vitessce @ git+https://github.com/LucaMarconato/easy_vitessce@unpin-dask",
    "pyqt5>=5.15.11",
    "lamindb>=1.15.2",
    "neuroglancer>=2.41.2",
    "bionty>=1.8.1",
    "ovrlpy>=1.0.1",
    "k3d>=2.17.0",
    "trame>=3.12.0",
    "trame-jupyter-extension>=2.1.4",
    "ipyvtklink>=0.2.2",
    "jupyter-black>=0.4.0",
    "anywidget>=0.9.21",
    "itk>=5.4.4.post1",
    "igneous-pipeline>=4.32.0,!=4.33.0,!=4.34.0",
    "dask>=2025.2.0",
    "ngff-zarr>=0.19.1",
]
